version: '3'

services:
  nginx:
    container_name: ${DOMAIN}_nginx
    build:
      context: ./nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        SERVER_NAME: ${DOMAIN}
    restart: always
    environment:
      VIRTUAL_HOST: ${DOMAIN}
    volumes:
      - code:/code
    depends_on:
      - php

  php:
    container_name: ${DOMAIN}_php
    build:
      context: ./php
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - code:/code
    depends_on:
      - mysql
      - wordpress

  mysql:
    container_name: ${DOMAIN}_mysql
    image: mysql:${MYSQL_VERSION}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    container_name: ${DOMAIN}_wordpress
    build:
      context: ./wordpress
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    volumes:
      - code:/code
    command: sh -c "test -f /code/index.php ||
                    (set -ex;
                    curl -o wordpress.tar.gz -fSL \"https://wordpress.org/wordpress-${WORDPRESS_VERSION}.tar.gz\";
                    tar -xzf wordpress.tar.gz --strip-components=1 -C /code;
                    cp /code/wp-config-sample.php /code/wp-config.php;
                    sed -i \"s/database_name_here/${MYSQL_DATABASE}/g\" /code/wp-config.php;
                    sed -i \"s/localhost/mysql/g\" /code/wp-config.php;
                    sed -i \"s/username_here/${MYSQL_USER}/g\" /code/wp-config.php;
                    sed -i \"s/password_here/${MYSQL_PASSWORD}/g\" /code/wp-config.php;
                    chown -R www-data:www-data /code;
                    rm wordpress.tar.gz)"

volumes:
    code:
    mysql_data:

networks:
  ${DOMAIN}:
    external: true